### PR TITLE
Adds onGetErrorMessage support for boolean, custom and color field

### LINKED ISSUE #392: Improved validation and conditional support for PropertyFieldCollection
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version
3.2.0

#### Desired Behavior
In https://github.com/microsoft-search/pnp-modern-search/pull/1282 I found a need to add some custom validation and conditional headers which seemed to be hard to do with the out of the box exposed methods/events available in https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldCollectionData.

It would be nice to have a possibility to use onGetErrorMessage on row level or similiar to validate on multiple fields. Instead of using field label: for this output it would only add a error message with what’s returned. It also should be triggered for the boolean field type as that currently does not seem to work.

When it comes to the conditional visibility of columns one could suggest to include a visible-property on field level. This would require an event such as onRowUpdate(currentItem, items, fields) or similar though. It also could be a predicate property isVisible={items =>.

This would make it easier to create more dynamic listings that has more advanced dependencies.

### PR DESCRIPTION
**Pull request by ellinge**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [X]
| New sample?      | [ ]
| Related issues?  | partially fixes #392

#### What's in this Pull Request?

I found out that boolean did not work with custom validation (onGetErrorMessage) on PropertyFieldCollection.

I added support for this and the color-field and custom-field types as well. In addition the onGetErrorMessage is triggered on row level also which ensures that changes on dependent fields can trigger a invalid item (and don't allow add/save).

The check is triggered after all required fields are set:
bild

The test sample from the screenshot above is setup in the following way:
```typescript
{
  id: "Sign",
  title: "Signed",
  type: CustomCollectionFieldType.boolean,
  defaultValue: true,
  onGetErrorMessage: (value, index, currentItem) => { 
    return value && currentItem.City == 'antwerp' ? 'You cannot check sign when City is Antwerp' : "";
  }
},
```
```typescript
{
  id: "color",
  title: "Color",
  type: CustomCollectionFieldType.color,
  defaultValue: "#ff0000",
  onGetErrorMessage: (value, index, currentItem) => {
    return value == '#ff0000' && currentItem.City == 'antwerp' ? 'You cannot set default color when City is Antwerp' : "" 
  }
},
```

### CODE REVIEW

**Comment by AJIXuMuK** [comment]
Hi @ellinge - this seems to me as a breaking change. You're changing a return value of `fOnValueChange` that can be used by developers.
We usually don't provide such a breaking changes.
Please, rewrite your code to return `void | Promise<void>`

**Comment by ellinge** [comment]
I think it was needed to make sure the state is updated before doing any validation of currentItem.
https://github.com/pnp/sp-dev-fx-property-controls/pull/395/files#diff-cd216594621aaa6009403ca07f6fb953e023f5179b6e54b4df3bdfb555667b88L62

I think it's related to onGetErrorMessage being async as well:
https://github.com/pnp/sp-dev-fx-property-controls/pull/395/files#diff-cd216594621aaa6009403ca07f6fb953e023f5179b6e54b4df3bdfb555667b88L202

Tried to simplify it since the validation was done in several places and I sometimes got a validation message for the "old value" since the state was not updated yet. Perhaps it can be solved in another way but I will have to give it another go since it was some time ago I did this.

**Comment by ellinge** [comment]
Perhaps it should be a breaking change if you look at how it's used.
https://github.com/pnp/sp-dev-fx-property-controls/pull/395/files#diff-cd216594621aaa6009403ca07f6fb953e023f5179b6e54b4df3bdfb555667b88R54 this is setting the item async. And the validation is then done disregarding if the state has been updated or not. See:
https://github.com/pnp/sp-dev-fx-property-controls/blob/7fb3a42fcf61e69c49b7ba589dfa941b7ada62cd/src/propertyFields/collectionData/collectionDataItem/CollectionDataItem.tsx#L195

**Comment by AJIXuMuK** [comment]
Thank you @ellinge for the updates!

**Pull request merged**
