### PR TITLE
Support for a color picker field within the Collection Data Panel control

### PR DESCRIPTION
**Pull request by johnnycardy**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | #326 

#### What's in this Pull Request?

Support for a color picker field within the collection data editor control. Utilises the Fluent UI ColorPicker control within a Callout.

### CODE REVIEW

**Comment by johnnycardy** [comment]
Screenshot of the functionality for context:

image

**Comment by AJIXuMuK** [comment]
Thank you @johnnycardy  for the PR!

It has been merged and will be included in the next release.

**Comment by bhoomesh-spe** [comment]
@AJIXuMuK  @johnnycardy - How can I integrate in Property Pane Collection Data? It is really helpful if you provide some link for the same. Thanks

**Comment by AJIXuMuK** [comment]
@bhoomesh-spe you can read the docs. There you can find how to use the control and eve provide custom rendering for fields: https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldCollectionData/

**Pull request merged**
