### PR TITLE
Added Feature: Role definition picker

### LINKED ISSUE #266: roleDefinition picker
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-property-controls/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
- [x ] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [   latest      ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

Hey , it would be nice to have a roleDefinition picker. So if an app wants to grant a specific permission we could have a picker that lets you specify what permission level to use.
for valid options we could use pnpjs sp.web.roleDefinitions()

Thanks!

### PR DESCRIPTION
**Pull request by gautamdsheth**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | fixes #266 

#### What's in this Pull Request?

This PR adds the `PropertyFieldRoleDefinitionPicker` control for the property pane.

There is also a minor docs fix so that file picker control is also surfaced in documentation.

Thoughts/Feedback ?

### CODE REVIEW

**Comment by russgove** [comment]
Hi Guatam,
Thanks for this! I'd be happy to test on a current project. Do you have this on a github repo somewhere I could pull it from?
Russell

**Comment by gautamdsheth** [comment]
Hey @russgove , thanks for this.
You can check it out at this location - 

https://github.com/gautamdsheth/sp-dev-fx-property-controls/tree/feature/roleDefinitionPicker

The docs are at this location:

https://github.com/gautamdsheth/sp-dev-fx-property-controls/blob/feature/roleDefinitionPicker/docs/documentation/docs/controls/PropertyFieldRoleDefinitionPicker.md

To test this, you can just download the project , npm install (use Node v8 or v6) and then gulp serve.

**Comment by russgove** [comment]
Hey, can we have it be an option to allow the user to select only ONE role
definition?

**Comment by russgove** [comment]
Hey, I am trying to use this in an spfx 1.10 app. The library is built with
an older version of spfx (1,3?)so when I pass the context property they are
incompatible.
Rather than passing the entire context as a property, can we just pass the
individual fields in the context that are needed by the control?
Thanks
Russell

**Comment by gautamdsheth** [comment]
Hey @russgove , thanks for the feedback, have added `multiSelect` property which can be set to false if you only want to allow single role. 

Regarding the webpart context, not sure what issue it is, the context object is the same that is used across other controls, are those impacted as well, will also try to investigate from my end as well ?

**Comment by AJIXuMuK** [comment]
Thank you @gautamdsheth for the great addition. It has been merged!

@russgove - the issue with `context` appears when you use `npm link` only. Please, test [beta version](https://pnp.github.io/sp-dev-fx-property-controls/beta/). It should work as expected

**Pull request merged**
