### PR TITLE
Added Format Code functionality to PropertyFieldCodeEditor property control

### PR DESCRIPTION
**Pull request by nanddeepn**
| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| Related issues?  | fixes https://github.com/pnp/sp-dev-fx-property-controls/issues/165

#### What's in this Pull Request?
Added Format Code functionality to PropertyFieldCodeEditor property control for languages including JSON, JavaScript, Sass, TypeScript", HTML, Handlebars, XML, css.
When the language is Plain Text, the "Format Code" button is hidden.

### CODE REVIEW

**Comment by nanddeepn** [comment]
Hi @AJIXuMuK 
Please review this PR. Thanks

**Comment by AJIXuMuK** [comment]
Hi @nanddeepn!
Thank you for the contribution!

Could you please check the markup of the element? In my tests "Format code" button location is ugly:
bad-markup

Another thing: you don't need to change all `loc` files. Please, make needed changes in `en-us.js` and we'll automatically translate them to other languages.

**Comment by nanddeepn** [comment]
Thanks @AJIXuMuK
I will look into this.

This looks fine in SharePoint local workbench, but not in hosted workbench.

Local Workbench
Localworkbench

Hosted workbench
hostedworkbench

**Comment by nanddeepn** [comment]
Hi @AJIXuMuK 
Fixed the layout for buttons: https://github.com/pnp/sp-dev-fx-property-controls/pull/261/commits/472494f4b9cbcb1ac2bf80bc0625a6c61ecabe24

**Comment by AJIXuMuK** [comment]
merged!
thanks @nanddeepn

**Pull request merged**
