### PR TITLE
Allow falsey keys as dropdown options

### PR DESCRIPTION
**Pull request by ellinge**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [X]
| New sample?      | [ ]
| Related issues?  | None

#### What's in this Pull Request?

I extended an existing checkbox, https://github.com/microsoft-search/pnp-modern-search/pull/1342,  with an additional option and wanted to keep false and true as valid options still for backward compabilty. But there's a `|| null` expression making all falsey options not valid as a key. And the underlying IDropdownOption does not allow it either in Fluent.

I've added som falsey possibilities in the sample test data:
```typescript
{
  key: false,
  text: 'False City'
},
{
  key: 0,
  text: 'Zero City'
}
```

Tried with key: '' as well and it works as long as you don't have required: true.
image

### CODE REVIEW

**Comment by AJIXuMuK** [comment]
Hello @ellinge - why `0` and `1` or `'true'` and `'false'` doesn't work for you?

**Comment by ellinge** [comment]
Because of this line:
https://github.com/pnp/sp-dev-fx-property-controls/pull/397/files#diff-6060c61d35d59c9162eb3eceb7b5a166281fd0a055894ff66b02d4b0d663ccf1L77
They will evaluate to false and send null to the dropdown component as selected key. Even if it works with these values if skipping this.

**Comment by AJIXuMuK** [comment]
Sorry @ellinge - I don't quite get the full picture. If you change the line to remove `|| null` - why is that not enough?
Why do you need to modify key implementation to support boolean type explicitly?

**Comment by ellinge** [comment]
The other changes are for typescript. Wouldn’t really need them but I would get a type error if trying to send a boolean.

Currently work around it by converting the values to a string so that false is not treated as null.
https://github.com/microsoft-search/pnp-modern-search/pull/1342/files#diff-a1b789c9595a432c17387fe38a9801f74e73729aaebe952c0b67bc891ceb161cL227

I don’t think there’s no type checking/interface involved in the line above so not an issue really. So technically just removing || null would suffice. But if someone else tried the component/interface directly they would get a type check error with false/true. This is for backward compability in our case so perhaps should not change the implementation in this case. It’s up to you.

**Pull request merged**
