### PR TITLE
Fixed an internal typo in the codebase

### PR DESCRIPTION
**Pull request by HiltonGiesenow**
| Q               | A
| --------------- | ---
| Bug fix?        | [ x]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | 

#### What's in this Pull Request?
Fixed an internal typo in the codebase

### CODE REVIEW

**Comment by HiltonGiesenow** [comment]
Is this repo still alive? I've got several PRs going back a few months at this point...

**Comment by AJIXuMuK** [comment]
@HiltonGiesenow - yes, it is alive but slow. Sorry for that. 
I will be spending some time reviewing PRs later this week.

**Comment by HiltonGiesenow** [comment]
Great stuff, thank you. Let me know if you need anything.

**Comment by AJIXuMuK** [comment]
Merged! thank you @HiltonGiesenow for the contribution!

**Pull request merged**
