### PR TITLE
Feature: added stock images support to file picker

### PR DESCRIPTION
**Pull request by gautamdsheth**
| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | NA

#### What's in this Pull Request?

1) Added support for stock images in the file picker property pane control
2) Minor fix in org assets - additional null check for thumbnail of libraries
3) Minor TSlint fix for number control - added semicolon

### CODE REVIEW

**Comment by AJIXuMuK** [comment]
Hi @gautamdsheth!
Thanks for that change!

I have one request... Could you please update the design of Stock Images tab to look alike any other tab in the picker.
Recent:
Screen Shot 2020-10-11 at 1 54 01 PM

Stock Images:
Screen Shot 2020-10-11 at 1 54 10 PM

**Comment by gautamdsheth** [comment]
hey @AJIXuMuK will try, not very good at CSS :(

**Comment by gautamdsheth** [comment]
Hey @AJIXuMuK , no luck with this so far unfortunately, it could be that this is rendered inside `iframe` so that's why styles couldn't be applied. Not sure how we can change this. Can you please take a look ?

**Comment by AJIXuMuK** [comment]
Hey @gautamdsheth,
I didn't know it's an iframe.

So I just updated styles a bit to look alike OOB control.

Thanks for the contribution!

**Comment by AJIXuMuK** [comment]
Hey @gautamdsheth,
I didn't notice the iframe...

So I just updated some styles to look it similar to OOB implementation.

Thanks for the contribution!

**Pull request merged**
