### PR TITLE
[Bug fix] Site Picker search for any input string

### LINKED ISSUE #386: Site Picker doesn't return sites with title with 2 or less characters
#### Category
- [x] Enhancement
- [X] Bug
- [ ] Question

#### Version
Please specify what version of the library you are using: [2.7.0]

#### Expected / Desired Behavior / Question
There are many sites with just 2 characters in the title, like TI, HR etc. I would like to find these sites typing one or two characters (maybe with component property that allow me to set minimun characters to type before run search).

#### Observed Behavior
These sites are missing in the result set when I type full title. The only way to retrive is typing multiple spaces (very strange, and not obvious for users)

#### Steps to Reproduce
1. Add PropertyFieldSitePicker to the Property Pane
2. Type search text with 2 or 1 characters
3. Sites with 2 or 1 characters on title cannot be found

### PR DESCRIPTION
**Pull request by milanholemans**
| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #386

#### What's in this Pull Request?

* Added missing semicolon
* Updated Site Picker component to search on any input string. Previously the site picker only searched when 3 chars were entered. Now the Site Picker component searches when 1 char is entered. This way sites like HR, IT, ... can be found.

### CODE REVIEW

**Comment by joelfmrodrigues** [comment]
@milanholemans Many thanks for the PR. Updated to target dev branch instead of master

**Comment by milanholemans** [comment]
Thanks @joelfmrodrigues . Indeed forgot to target the right branch (again) 😃.

**Comment by joelfmrodrigues** [comment]
> Thanks @joelfmrodrigues . Indeed forgot to target the right branch (again) 😃.

I do it all the time 😆

**Comment by joelfmrodrigues** [comment]
@milanholemans many thanks for the great improvement, this is now merged

**Pull request merged**
